# Generated by Django 4.2.4 on 2023-10-12 17:32

from django.db import migrations, models
import music_space_api.models


class Migration(migrations.Migration):
    dependencies = [
        ("music_space_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=music_space_api.models.generate_unique_code,
                max_length=8,
                unique=True,
            ),
        ),
    ]
